HAIDER
	;
	;
	;	
	Q
	;
DEMO
	WRITE # ; CLEAR SCREEN
	WRITE "LAB UTILITES"
	WRITE !,!,! ; NEW LINE
	WRITE "1) FILL ORDER",!
	WRITE "2) ACCESSION SAMPLE",!
	WRITE !,!,!
	IF $DATA(^HAIDER) DO
	. WRITE "Last time you chose",^HAIDER
	. WRITE !
	READ "Choose Option # ",OPTION
	W !
	IF OPTION=1 WRITE #,"YOU ENTERED FILL ORDER SCREEN" DO STORE(OPTION) QUIT
	IF OPTION=2 WRITE #,"YOU ENTERED ACC SAMPLE" DO STORE(OPTION) QUIT
	IF OPTION'=1,OPTION'=2 WRITE #,"WRONG ENTRY" D CLEARDB HANG 3 GOTO DEMO
	;		
	QUIT
	;
STORE(CHOICE)
	SET ^HAIDER=CHOICE
	QUIT
	;	
CLEARDB
	KILL ^HAIDER
	QUIT
	;