ZAA02GSCRCH1 ;PG&A,ZAA02G-SCRIPT,2.10,INTERFACE ROUTINE FOR COLUMBIA MED PLAN;09FEB94  14:26;12DEC94 10:03A;;28APR99  09:15
 ;
LKCC ; LOOKUP CCs
 S PROVC="c"_($G(n(1))+2) G LKPV0
LKATT ; LOOKUP ATTENDING
 S PROVC="PROVA" G LKPV0
LKPV ; LOOKUP PROVIDER
 S PROVC="PROV"
LKPV0 Q
 ;
 ; Used in printing CCs in footer
CCS ; PROCESS CC address on report
 S c=C+.00001 F j=1:1:6 I $G(@VDOC@("CC"_j_"A"))]"" S C(c)="",c=c+.00001 F k="","A","B","C","D" I $G(@VDOC@("CC"_j_k))]"" S C(c)=$S(k="":"cc: ",1:"")_@VDOC@("CC"_j_k),c=c+.00001
 K c Q
CCCT S cT=0 F j=1:1:6 I $G(@VDOC@("CC"_j_"A"))]"" S cT=cT+1 F k="","A","B","C","D" I $G(@VDOC@("CC"_j_k))]"" S cT=cT+1
 K:'cT cT Q
 ;
DRUG ; MACRO FOR DISPLAYING PATIENT MEDICATION
 K MC Q:'$G(INP("PIN"))
 N (ZAA02G,ZAA02GP,INP,MC,REFRESH) S Y=$$IN^KDISP(INP("PIN")) I '$D(KDISP) W *7 Q
 S REFRESH="",Y="11,4\RLHSG1O127\1\PATIENT MEDICATIONS\  DATE           MEDICATION                    PHYSICIAN   "
 S Y(0)="\EX\\$$DT^ZAA02GSCRCH1(-TO);10`$P(TO,""|"",2);30`KDISP(+TO,$P(TO,""|"",2));15"
 S ZAA02GPOPALT=$P($T(LOOKD),";",2,99) D ^ZAA02GPOP I X'[";EX" S MC=$P(X,"|",2),MC=$E(MC)_$TR($E(MC,2,99),"ABCDEFGHIJKLMNOPQRSTUVWXYZ","abcdefghijklmnopqrstuvwxyz")
 Q
DT(D) N (ZAA02G,D) D DATE^ZAA02GSCRCHM Q DT
 ;
MAIL I $D(^ZAA02GMAIL) S J=$D(ZAA02GID) D ^ZAA02GMANQ K:'J ZAA02GID I $D(ZAA02GM) S %R=24,%C=+ZAA02GM,REFRESH="3:23" W @ZAA02GP,$P(ZAA02GM,";",2,9) K ZAA02GM
 Q
 ;
LOOKD ;S S=$P(TO,""|""),S2=$P(TO,""|"",2) S:S=0 S="""" F  S:S2="""" S=$O(KDISP(S)) S:S S2=$O(KDISP(S,S2)) S TO=S_""|""_S2 S:TO=""|"" TO="""" Q:TO=""""  Q:S2'=""""
 ;
SITEC ; PROCESS CHANGES IN SITEC FROM ID BLOCK
 S INPS("P1")=X,opi="PDSP;PROV;""""" X:$G(INP("MR"))="" op Q
