ZAA02GSCMUT ;PG&A,ZAA02G-MTS,1.20,MISC UTILITY OPS;30DEC94 4:14P;;;20MAR96  10:43 [ 02/25/97   5:22 PM ]
C ;Copyright (C) 1995, Patterson, Gray & Associates, Inc.
 ;
XP ; CHECK VALIDITY OF XP DIRECTORY
 S (A,B)="" F  S A=$O(@ZAA02GSCM@("XP",A)) Q:A=""  F  S B=$O(@ZAA02GSCM@("XP",A,B)) Q:B=""  S C=+B D XP1
 Q
XP1 I '$D(@ZAA02GSCM@("EXAM",C)) W "EXAM ",C," NOT FOUND FOR CODE ",A,! G XPD
 I ^(C)'[A W "EXAM ",C," DOES NOT CONTAIN CODE ",A,! G XPD
 Q
XPD K @ZAA02GSCM@("XP",A) Q
 ;
SEARCH I $D(@ZAA02GSCM@("XP",A)) K ^ZAA02GTSCM($J) S (B,C)="" F  S B=$O(@ZAA02GSCM@("XP",A,B)) Q:B=""  F  S C=$O(@ZAA02GSCM@("XP",A,B,C)) Q:C=""  S ^ZAA02GTSCM($J,10000000-C)=""
 S SRC="^ZAA02GTSCM($J)"
