ZAA02GSCRFX2 ;PG&A,ZAA02G-SCRIPT,2.10,FAX OPERATIONS-2;7DEC94 2:39P;;;Wed, 10 DeC 2014  10:26
 ;Copyright (C) 1993, Patterson, Gray & Associates, Inc.
 ;
 ;
LOG S DONE=1,ZAA02G("d")=0,LN=0 D DATE^ZAA02GSCRER
LOG1 S B=@VDOC@("B"),JOB=^("JOB"),ZAA02GSCR=^("ZAA02GSCR"),C=^("C") D:'LN LOGT W ?5 F J=1:1:12 W "------"
 W !?5,"FAX JOB #: ",?16,JOB,?30,"TO:",?40,$P(B,"\",13),!?5,"STATUS:",?16,$P(B,"\",3),?30,"FAX #: ",?40,$P(B,"\",4),!?5,"REPORT #:",?16,$P(B,"\",2)
 W ?30,"PATIENT: ",?40,$P(B,"\",31),!?30,"PROVIDER:",?40,$P(C,"`",7)
 S LN=LN+5,B=$O(@VDOC) I $P(B,"_")["FX" K @VDOC S XDC=B W ! X:LN>35 "S LN=0 W #" G LOG1
 W # Q
LOGT N A S A=$E($P(@ZAA02GSCR@("PARAM","BASIC"),"|"),1,35) W !!!!!!!!!!!!!!?5,"ZAA02G-FAX REPORT",?38-($L(A)\2),A,?55,$J(DT_"  "_TM,20),!
 Q
TEST S VDOC="^ZAA02GWP(.9,DP,XDC)",DP=12,XDC="F",XDC=$O(@VDOC) Q:$E(XDC)'="F"  G LOG
 ;
LOGALL G:$G(^ZAA02GSCR("PARAM","REMOTEFAX"))&'$D(COMPL) REMALL D LOGINIT Q:'$D(@ZAA02GSCR@("TRANS",JOB,.011))  S C=^(.011) G LOGER1
LOGERR G:$G(^ZAA02GSCR("PARAM","REMOTEFAX"))&'$D(COMPL) REMERR D LOGINIT Q:'$D(@ZAA02GSCR@("TRANS",JOB,.011))  S C=^(.011) G:$P(B,"\",10)'=3 IO S FAILED=$P(B,"\",10)
LOGER1 I $D(@ZAA02GSCR@("PARAM","FAX")),$P(^("FAX"),"\",27)]"" S DV=$P(^("FAX"),"\",27) G LOGER2
 S DV=$P(B,"\") I DV[" -P" S DV=$P(DV," -P",2)_"Q",DD="" F  S DD=$O(^LPT(DD)) Q:DD=""  I ^(DD)=DV S DV=DD Q
 Q:'$D(^ZAA02GWP(96,DV))  X:$D(@ZAA02GSCR@("PARAM","DEVICE")) ^("DEVICE")
LOGER2 I DV]"" S PG="ALL",DOC="FAX-LOG: "_JOB,Y("XECUTE")="D LOG^ZAA02GSCRFX2",Y("JOB")=FAX,Y("B")=B,Y("C")=C,Y("ZAA02GSCR")=ZAA02GSCR,CP="FX"_$P(ZAA02GSCR,"ZAA02GSCR",2) S:$D(@ZAA02GSCR@("PARAM","BATCH",CP)) ZAA02GBATCH=CP S CP=1 D QUEUE^ZAA02GWPP8 K ZAA02GBATCH
 G IO
 ;
T S A=19929 D LOGERR
LOGINIT D REMINIT Q:JOB<0  S FAX=A,B=^(10000-A),JOB=$P(B,"\",2),ZAA02GSCR=$S($G(^ZAA02GSCR("PARAM","DATABASE"))]"":^("DATABASE"),1:"^ZAA02GSCR")
 Q
REMERR D REMINIT Q:JOB<0  S ^ZAA02GFAXQ("COMPLETED",A)="LOGERR" Q
REMALL D REMINIT Q:JOB<0  S ^ZAA02GFAXQ("COMPLETED",A)="LOGALL" Q
REMLOG D REMINIT Q:JOB<0  S ^ZAA02GFAXQ("COMPLETED",A)="NOLOG" Q
REMINIT S JOB=-1 Q:'$D(^ZAA02GFAXQ("DIR",10000-A))  S JOB=2 Q
 ;
COMPLETE N  S COMPL=1 F JJ=1:1 S A=$O(^ZAA02GFAXQ("COMPLETED","")) Q:A=""  S B=$G(^(A)) K ^(A) Q:B=""  D @B
NOLOG ; just update IO parameters
 G:$G(^ZAA02GSCR("PARAM","REMOTEFAX"))&'$D(COMPL) REMLOG D LOGINIT Q:$G(JOB)=""  Q:'$D(@ZAA02GSCR@("TRANS",JOB,.011))
IO Q:'$D(@ZAA02GSCR@("TRANS",JOB))
 I $G(^(JOB,.011,"IO"))'[",F*" S ^("IO")=$E($G(^("IO")),1,200)_",F*"
 S ^("IO")=$P(^("IO"),",F*")_",F"_$TR($H,",",":")_":"_$P(B,"\",4)_$S($D(FAILED):"F",1:"")_":"_$P(^("IO"),",F*",2,99) K FAILED
 I $P(@ZAA02GSCR@("TRANS",JOB),"`",13)["F" S K=$E($TR($P(^(JOB),"`",13),"F~ ")_"~  ",1,4),$P(^(JOB),"`",13)=K,$P(@ZAA02GSCR@("DIR",99,10000000-JOB),"`",13)=K Q
 Q
 ;
DIRECT D INIT^ZAA02GFAXQ K X S BL=22,X(2)=FAXN,X(34)=$S($D(OVR):"S OVR="""_OVR_"""",1:""),X(7)="*",X(1)=$S($D(^ZAA02G("$I")):"",$D(^ZAA02GFAXQ(.6,ZAA02G(3))):^(ZAA02G(3)),1:"")
 S:$D(FAXTO)#2 X(4)=FAXTO S:$D(FAXSUB) X(3)=FAXSUB S:$D(FAXFROM) X(1)=FAXFROM S:$D(FAXTOF) X(5)=FAXTOF S:$D(FAXORG) X(6)=FAXORG
 S B=^ZAA02GFAXC("DEFLTS"),X(11)=$S($P(B,"\",1)="":"Y",1:$P(B,"\",1)),X(14)=$S($P(B,"\",4)="":"Y",1:$P(B,"\",4)),X(15)=$P(B,"\",5),X(16)=$P(B,"\",6)
DIR4 D ^ZAA02GFAXQ1 G DIRE:X(5)="",DIRE:FNC["EX" S C=$TR(X(5),"0123456789,- FAX","0123456789") I $L(C)>7,10'[$E(C),$S($D(ZAA02G("d")):'ZAA02G("d"),1:1) D ATT^ZAA02GFAXQ G DIR4:Y=7
 S FAXTO=X(4),FAXTOF=X(5),FAXFROM=X(1),FAXORG=X(6),FAXSUB=X(3) S:FAXTO'="" ^ZAA02GFAXP($TR(FAXTO,lc,uc))=FAXTOF_"`"_FAXTO_"`"_X(7)_"`"_X(8)_"`"_X(9)_"`"_X(10)_"`"_X(11)_"`"_X(12)_"`"_X(13)_"`"_X(14)_"`"_X(15)_"`"_X(16)_"`"_FAXORG
 S:'$D(^ZAA02G("$I")) ^ZAA02GFAXQ(.6,ZAA02G(3))=X(1) S STM="" I X(9)_X(10)'="" D DELAY^ZAA02GFAXU G:STM="" DIRE
 F C=7:1:10 I X(C)="*" S X(7)=C-6 Q
 Q
DIRE K X Q
STATUS K Y S Y="40\CRHLUD\1\ZAA02G-FAX\\Send this Document,Resend a ZAA02G-FAX job,Cancel ZAA02G-FAX Job,Document Status,Quit" S:'$D(BL) BL=22 S %R=BL-8,Y(0)="\EX" D ^ZAA02GFAXU2 Q:X["EX"  Q:X=5
 Q:X=1  S TYP=1,NX=14,SEL=0,EX="I 0",TFM=0 D @$S(X=2:"RESEND^ZAA02GFAXQ",X=3:"CANCEL^ZAA02GFAXQ",1:"^ZAA02GFAXS") G STATUS
 ;
REPRINT ; REPRINT JOBS THAT WEREN'T FAXED - CALL BY HAND
 D ^ZAA02GSCRPW W ZAA02G("F") X ^ZAA02G("TERM-OFF")
 K TRANS R "PRINT UP TO QUEUE DATE (MM/DD) - ",DT,!
 R "Using what distribution list - ",DISTR,!
 S A="" F  S A=$O(^ZAA02GFAXQ("DIR",A)) Q:A=""  S B=^(A) Q:$P(B,"\",6)[DT  D RP1
 D RP2
 Q
RP1 S C=$P(B,"\",3) Q:C["Sent"  Q:C["CANCEL"  S D=$P(B,"\",11)["St. J",^REPR(D,$P(B,"\",13)_" "_A)=A
 Q
RP2 F H=0,1 S ZAA02GSCR="^ZAA02GSCR"_$E(1,'H+1),A="" W !,"HOSPITAL - ",H R "  PRINTER-",DV,! F  S A=$O(^REPR(H,A)) Q:A=""  S B=^(A),C=^ZAA02GFAXQ("DIR",B),DOC=$P(C,"\",2) I $D(@ZAA02GSCR@("TRANS",DOC)) D RPPRNT
 Q
RPPRNT W ^(DOC),! S TITLE="Copy to:  "_$P(C,"\",13)
 N (ZAA02GSCRP,DOC,ZAA02GSCR,DV,DISTR,ZAA02G,ZAA02GP,TITLE) S INP("TITLE")=TITLE D PR3^ZAA02GSCRER2
 Q
REQUEUE ; REQUEUE FAXES THAT ARE EITHER REGULAR OR READY
 S A="" F J=1:1:3000 S A=$O(^ZAA02GFAXQ("DIR",A)) Q:A=""  I ^(A)["READY"!(^(A)["Regular")!(^(A)["Ready") S ^ZAA02GFAXQ(.9,10000-A)=""
 J ^ZAA02GFAXC Q
