ZAA02GSEND9 ;PG&A,ZAA02G-SEND,1.36,MODEM TRANSFER (Kermit-XFR);11APR96 2:24P;;;05DEC96  23:49
 ;PG&A, 1993
TS S ER=0,KP="T",MODEM=20,GLOB="^ZAA02GKERMIT($J)" D INIT^ZAA02GSENDA,SEXE Q
 ;
SEXE S FILE=.9,PTR="SB1" D CLR S @GLOB@(0,"START")=$H,@GLOB@(0,"TYPE")="SEND",TM=0
 S:MODEM=0 KP="" S:MODEM=$I KP=""
 I KP["D" S RP="" D SEXD
SEXE0 G:PTR="" SEXIT S L=$P($T(@PTR),";",2),SP=$P(L,",") D @$P(L,",",2) E  I $P(L,",",3)]"" S PTR=$P(L,",",3) G SEXE0
SEXE1 D SEND D:KP["D" SEXD G:WO SEXE2 D REC I 'F,RP="Y" D:RN<SN SEXE6 I 'F,RN=SN S (SN,SEQ)=SEQ+1,LN=$S(SEQ#64=0:LN+64,1:LN) G SEXE4
 I F=2,SP="B"!ER G SERR
SEXER S:$S(SN:1,F=2:0,1:1) CT=CT+1,TT=TT+1 G SEXE1:CT<NERR,SERR
SEXE2 I SEQ-$O(WO(""))<WO S:SN=SEQ SEQ=SEQ+1,LN=$S(SEQ#64=0:LN+64,1:LN) D RECX G:$C(A)'=RH SEXE4 D REC0 G SEXE3
 D REC I 'F,RP="Y" K WO(RN) S CT=0 G SEXE2
SEXE3 I 'F,RP="Y" K WO(RN) S CT=0 G SEXE0
 I 'F,RP="N" S:'$D(WO(RN)) RN=$O(WO("")) G:'RN SEXE0 S SD=WO(RN),SN=RN G SEXER
 I 'F,RP="E" S SD=RD,ER=3 D MAXERR G EXIT
 I F=2 G:ER SERR S RN=0,RP="N",F=0 G SEXE3
 I F=1 S SN=$O(WO("")) I SN S SD=WO(SN) G SEXER
 G SEXE0
SEXE4 S PTR=$P(L,",",4) G SEXE0
SEXE6 F RN=RN:0 D REC Q:F  Q:RN=SN
 Q
SERR G:PTR="SB7" SEXIT S PTR="SB7",SN=SEQ G SEXE0
SEXIT G EXIT
EXIT I ER D CLR U 0
 S @GLOB@(0,"STOP")=$H,@GLOB@(0,"TBYTES")=TBY,@GLOB@(0,"ERROR")=+$G(ER) K CC,PTR,SP,SN,X,SD,TBY,SBY,RD,R8,S8,CS,SA,SC,KP,SPS,F,RP,SH,CRC Q
SEND I $L(SD)<95 S X=$C($L(SD)+35,SN#64+32)_SP_SD,CS=0 X CRC S P=SH_X_$C(CS\64#4+CS#64+32)_SE
 I $L(SD)>94 S X=$C(32,SN#64+32)_SP_$C($L(SD)+1\95+32,$L(SD)+1#95+32),CS=0 X CRC S X=X_$C(CS\64#4+CS#64+32)_SD,CS=0 X CRC S P=SH_X_$C(CS\64#4+CS#64+32)_SE
SEND1 U MODEM H SPS F I=1:1:SA W *SC
 W P Q:KP'["T"  U 0 W ZAA02G("HI"),"SENDING PACKET - ",SN,", TYPE - ",SP,"  DATA: ",$TR(P,$C(1,13),""),$S(P[$C(13):"<CR> ",1:"  ") Q
 Q
SB ; send batch sequence - TYPE,DATA LOGIC,DATA ESCAPE,NEXT
SB1 ;S,SPARM,,SB1R; SEND S PACKET WITH SEND PARMETERS
SB1R ;S,SPARM1,SB2,; PROCESS PARAMETERS
SB2 ;F,SFILE,SB5,SB3; SEND FILE SPECS
SB3 ;D,SDATA,SB4,SB3; SEND DATA
SB4 ;Z,SEOF,,SB2; END OF FILE
SB5 ;B,SEOB,,; END OF BATCH
SB7 ;E,MAXERR,,; MAX ERRORS
 ;
RECX I $TR(KP,"TD","")'=KP F I=1:1:6 U 0 R *A:0 G:A>0 TRAP:$C(2,3,24)[$C(A) D:A>0 TRACE:"tT"[$C(A) U MODEM R *A:0 Q:$C(A)=RH  I KP["T",A>31 U 0 W ZAA02G("LO"),*A
 I $TR(KP,"TD","")=KP F I=1:1:6 U MODEM R *A:0 Q:$C(A)=RH
 Q
REC S F=2 I $TR(KP,"TD","")'=KP F I=1:0:ST U 0 R *A:0 G:A>0 TRAP:$C(2,3,24)[$C(A) D:A>0 TRACE:"tT"[$C(A) U MODEM R *A:1 Q:$C(A)=RH  S:'$T I=I+1 G:I=ST REC1 I $T,KP["T",A>31 U 0 W ZAA02G("LO"),*A
 I $TR(KP,"TD","")=KP F I=1:0:ST U MODEM R *A:1 Q:$C(A)=RH  S:'$T I=I+1 G:I=ST REC1
REC0 S F=2 R *A:ST G REC1:'$T,REC:$C(A)=RH S RZ=A-32,CS=A G:RZ=0 RECL G REC1:RZ<1 R A#RZ:ST G REC1:'$T
REC2 S RN=$A(A)-32,RP=$E(A,2),X=$E(A,1,RZ-1),RD=$E(A,RZ>94*3+3,RZ-1) X CRC S CS=CS\64#4+CS#64,F=$A(A,RZ)-32'=CS,RN=$S('WO:LN+RN,RN>15&(RN<49):LN+RN,1:RN+16#64+LN+(SEQ#64>31*64)-16)
REC1 Q:KP'["T"  Q:F=2  U 0 W !,ZAA02G("LO"),"RECEIVED PACKET - ",RN,", TYPE - ",RP,"  DATA: ",$TR(A,$C(1,13),""),$S(A[$C(13):"<CR> ",1:"  ")
 W ! Q:'WO  S AA="" W "WINDOW-" F J=1:1 S AA=$O(WO(AA)) Q:AA=""  W AA," "
 W ! Q
RECL R B#5:ST S X=$E(B,1,4) X CRC S CS=CS\64#4+CS#64,F=$A(B,5)-32'=CS I F G REC1
 S X=$A(B,3)-32*95+$A(B,4)-32,CS=A,RZ=X+5 R X#X:ST S A=B_X I '$T S F=2 G REC1
 G REC2
TRACE S KP=$TR(KP,"TD","DT") D:KP["D" DISP^ZAA02GSENDA Q
TRAP S SD="CONTROL STOP FROM USER",ER=1,F=2 I 1 Q
 ;
SEXD U 0 D:RP="" DISP^ZAA02GSENDA S %R=12,%C=33 W @ZAA02GP,SBY\1000,"K,",TBY\1000,"K   " S %R=13 W @ZAA02GP,TBY\($P($H,",",2)-TM+.01),"   "
 S %R=15,%C=53 W @ZAA02GP,$J(TT,2) S %C=33 I $E(PTR)="S" W @ZAA02GP,SN S %C=43 W @ZAA02GP,SP Q
 W @ZAA02GP,RN S %C=43 W @ZAA02GP,RP Q
SPARM D SPARM^ZAA02GSENDA I 1 Q
SPARM1 D SPARM1^ZAA02GSENDA,CTINIT^ZAA02GSENDB Q
SFILE S FILE=$O(@GLOB@(0,"FILE",FILE)),SBY=0 I FILE]"" S SDB="",(FILEN,SD)=$S($D(@GLOB@(0,"FILE",FILE)):@GLOB@(0,"FILE",FILE),1:FILE),%G=$G(@GLOB@(0,"FILE",FILE,0)) S:'TM TM=$P($H,",",2)
 Q:'$T  I KP["D" U 0 S %R=11,%C=33 W @ZAA02GP,$E(SD_$J("",20),1,20)
 I 1 S SD=$P(SD,"(") Q
 S:'TM TM=$P($H,",",2) I 1 Q
 ;
STOUT I KP["T" U 0 W "TIMEOUT"
 Q
SDATA S WO=SW X SDATA I SDB]"" S SN=SEQ S:WO WO(SN)=SD
 Q
SEOF I $O(WO(""))="" K WO S WO=0,SD="",SN=SEQ,PTR="SB4" Q
 D REC I 'F,RP="Y" K WO(RN) G SEOF
 S SD=WO(RN),$P(L,",",4)="SB4" G SEXER
SEOB S SD="" I 1 Q
MAXERR S:'ER SD="MAXIMUM ERROR COUNT REACHED",ER=2 S @GLOB@(0,"ERRORR")=SD,ST=1 I 1 Q
CLR U MODEM F I=1:1 R A:1 Q:'$T
 Q
DTM ;C 10 O 10:("R":"MUMPS.EXE") S (C,S)="" U 0:EM=0 F  U 10 R *A U 0 W A,*13 R C
 Q
DTMX S A=$P($T(DTM),";",2,9),ZAA02G(1)=0 S DV=5 O DV X ^ZAA02G("ECHO-OFF") U DV R B:0,B:1 W A,*13 R A U 0 W A,!
 S (A,B,C,D,S)="",A=$O(^ZAA02GKERMIT(A)),B=$O(^(A,B)) F  S:D="" C=$O(^ZAA02GKERMIT(A,B,1,C)),D=^(C) S L=$A(D),D=$E(D,2,255),S=S+1 U DV R E W *13 I E'=L U 0 W S,"-",E," ",L,! R CCC
