ZAA02GSCRML ;PG&A,ZAA02G-SCRIPT,2.10,ZAA02G-MAIL INTERFACE;14FEB96 5:26P;;;07OCT99  14:53
 ;Copyright (C) 1984, Patterson, Gray & Associates, Inc.
 ;
 ; TO ADD ^ZAA02GMAIL TO ZAA02GSCRIPT - USE TRANS AS LINK VARIABLE
 ;
 ;
TR ;UPDATE ^ZAA02GMAIL USER FILE WHEN TR IS CHANGED
 Q
 Q:'$D(^ZAA02GMAIL(1))
 S X=$G(@ZAA02GSCRT@("PARAM","USER",ID)),X=$TR(X,"abcdefghijklmnopqrstuvwxyz","ABCDEFGHIJKLMNOPQRSTUVWXYZ")
 S UID=$P(X,"\",30),UNM=$P(X,"\")_","_$P(X,"\",2),UPW=$P(X,"\",3),UST="ACTIVE",ULK=ID,UDP="TR" I UID'="",'$D(^ZAA02GMAIL(4,UID)) S UID=""
 I UID="" S (REC,ADT,UDT,UID)=""
 I UID'="" S X=^ZAA02GMAIL(4,UID,0),ADT=$P(X,"`"),UDT=$P(X,"`",2),REC=^(1),UDP=$P(X,"`",6)
 D FILE^ZAA02GMAMU1 S $P(@ZAA02GSCRT@("PARAM","USER",ID),"\",30)=UID Q
 ;
ALL S ZAA02GSCRT=$S($D(@ZAA02GSCR@("PARAM","USER FILE")):^("USER FILE"),1:ZAA02GSCR)
 S ID="" F JJ=1:1 S ID=$O(@ZAA02GSCRT@("PARAM","USER",ID)) Q:ID=""  D TRQ
 ;
MENU S YY=$L($P(Y,";"),"\"),$P(Y,"\",YY-1)="Electronic Mail:MAIL^ZAA02GSCRML\Quit\",$P(Y,";",2)=$TR($P(Y,";",2),"Q","")_"EQ"  Q
 ;
MAIL D MAIL1 D HEAD^ZAA02GSCRIPT Q
MAIL1 N (ZAA02G,ZAA02GP,TRANS) D ^ZAA02GMAIL
STAT ; CALLED FROM ID BLOCK FOR MAIL STATUS
 I $D(^ZAA02GMAIL) D ^ZAA02GMANQ K ZAA02GID I $D(ZAA02GM) S %R=24,%C=+ZAA02GM W @ZAA02GP,$P(ZAA02GM,";",2,9) K ZAA02GM
 Q
