ZAA02GBLKFORAPPT ;;04/07/2015 12:05:26
 S EZ=1
 K ^SORT($J)
 D EZ^ZAA02GVBAS
 S RES=59,DATE=20190506
 S SLOT="" F  S SLOT=$O(^ZAA02GSCH(1,"DET",RES,DATE,SLOT)) Q:SLOT=""  D
 . S DAY=$$JUL^IDATE(DATE)#7
 . S DAYPCE=DAY+$S(DAY>3:-3,1:4)
 . S DATE1=$O(^ZAA02GSCH(PEZ,"PARAM","RES-TMPL",RES,DATE))
 . S TEMP=^ZAA02GSCH(PEZ,"PARAM","RES-TMPL",RES,DATE1) ; get template
 . S BLKDATA=$TR($S($D(^ZAA02GSCH(PEZ,"PARAM","RES-TMPL",RES,0,DATE,DAYPCE+.2)):^(DAYPCE+.2),1:^ZAA02GSCH(PEZ,"PARAM","TMP",TEMP,DAYPCE+.2)),$C(0,126)) ; blocks
 . S BLK=$P(BLKDATA,"+",SLOT)
 . I BLK="" Q
 . S BLK=$A(BLK)
 . S BLKDESC=$P(^ZAA02GSCH(PEZ,"PARAM","BLK",BLK),"|",2)
 . S ^SORT($J,RES,DATE,SLOT)=BLKDESC
