ZAA02GSCRADS ;;19JAN95 2:39P;;;05SEP2006  11:26
 ;
LOAD ; LOADS INP ARRAY FOR ID WITH PATIENT INFO. GIVEN ACCOUNT #
 N PRG S PRG=$S($D(^MSCG("ZAA02GSCRIPTPRG")):^("ZAA02GSCRIPTPRG"),1:"^ZAA02GADSGEN")
 S:$D(^MSCG("NASSAU")) PRG="^ZAA02GADSNAS" S:$D(^MSCG("FILMSJ")) PRG="^ZAA02GADSSJ"
 I $D(@ZAA02GSCR@("PARAM","ADS-LOOKUP")) S PRG=^("ADS-LOOKUP")
 B:PRG=""
 D @PRG
LOAD1 S K=0
 F J=1:1 S A=$P("MR,PATIENT,DOB,CONSULT,REV,CC1,CC2,CC3,PROC1,PROC2,DS,SITEC",",",J) Q:A=""  I $D(INP(A)) S K=K+1,opi(K)="PDSP;"_$P("MR,PATIENT,DOB,CONSULT,AUTOFAX,CC1,CC2,CC3,PROC1,PROC2,DOS,SITEC",",",J)_";INP("""_A_""")"
 I $D(SITEDIST) S K=K+1,opi(K)="PDSP;DIST;INP(""SITEC"")"
 S opi=K,SRF=rf,rf=ZAA02G("HI") x:K op S rf=SRF K SRF,A
 I 1 Q
 Q
LOOKMR ; LOOKUP BY ACC# OR PATIENT NAME FROM ACCT# FIELD
 I X?1N.E G LOAD
 I X?1"M"1N.E,$O(^MK($E(X,2,99),"")) S X=$O(^MK($E(X,2,99),"")) G LOAD
 I X?9N,$O(^SK(X,"")) S X=$O(^SK(X,"")) G LOAD
 D LOOKUP S X=$G(INP("MR")) Q
LOOKMR1 ; LOOKUP BY MR# OR PATIENT NAME FROM MR# FIELD
 I X?1"A"2.N S X=$E(X,2,9) D LOAD G LOOKMR2
 I X?1.8N,$O(^MK(+X,"")) S X=$O(^MK(+X,"")) D LOAD G LOOKMR2
 D LOOKUP
LOOKMR2 S X=$G(INP("PROC2")) Q
LOOKMR3 D LOOKMR1 S X=INP("MRN"),opi="PDSP;MR;X" X op q
 ;
LOOKUP ; LOOKUP IN THE ADS PATIENT FILE BY NAME
 S X=$TR(X,LC_"?",UP) D:X[" " STRIP S PDOB=$P(X,"=",2),X=$P(X,"="),PATD=$P(X,"/",2),PAT=$P(X,"/"),PT=$E($P(PAT,",",2)),PAT=$E($P(PAT,","),1,5),REFRESH=1 S:PT'?1U PT="" G:$L(PDOB_PAT)=0 LOOKE
 I $E($O(^PK(PAT)),1,$L(PAT))'=PAT G LOOKE
 I PT'="" S i=PAT F jj=1:1 S i=$O(^PK(i)) Q:i=""   Q:$E($O(^PK(i)),1,$L(PAT))=PAT&($E(i,6)=PT)  I $E($O(^PK(i)),1,$L(PAT))'=PAT G LOOKE
 D LOOK1 S tt=+REFRESH,td=$P(REFRESH,":",2) D AP0^ZAA02GFORM4
 I PAT[";EX" S X="" G LOOKE
 S X=$TR($P(PAT,"|",2,3),"|","/") S:X_" "["/1 " X=$P(X,"/") D LOAD S X=INP("PATIENT")
LOOKE K i,jj,PAT Q
 ;
LOOK1 N:1 (ZAA02G,ZAA02GP,PAT,PATD,PT,PDOB,REFRESH) S Y="15,7\RLHS\1\PATIENT LOOKUP\   NAME                    DOB       ACCNT #      MR #  "
 S Y(0)="\EX\\$S($L($P(^PTG(S2,S3),"":"",3)):$P(^(S3),"":"",3),1:$P(^GRG(S2),"":"",7));23`$$DOB^ZAA02GSCRADS($P(^PTG(S2,S3),"":"",12));10`S2_$S(S3>1:""/""_S3,1:"""");8R`$P(^(S3),"":"",11);11R\"
 S Y(0)=Y(0)_PAT_"\\\"_PAT_"z"
 S ZAA02GS1="S S=$P(TO,""|""),S2=$P(TO,""|"",2),S3=$P(TO,""|"",3)" I PDOB]"" S:PDOB?6.8N PDOB=$E(PDOB,5,8)_$E(PDOB,1,4) S:PDOB["/" PDOB=$P(PDOB,"/",3)*100+$P(PDOB,"/")*100+$P(PDOB,"/",2) S:$L(PDOB)=6 PDOB=190000+PDOB S:PDOB'?8N PDOB=""
 I $G(PDOB)="" S ZAA02GPOPALT=$P($T(LOOKT),";",2,99)
 I $G(PDOB)]"" S ZAA02GPOPALT=$P($T(LOOKT+1),";",2,99)
 D ^ZAA02GPOP S PAT=X Q
DOB(X) Q:$L(X)=6 $E(X,3,4)_"/"_$E(X,5,6)_"/19"_$E(X,1,2) Q $E(X,5,6)_"/"_$E(X,7,8)_"/"_$E(X,1,4)
 ;
LOOKT ;X ZAA02GS1 F jj=1:1 S:S2_S3="""" S=$O(^PK(S)) S:jj=999 TO="""" S:S]TEN TO=""""  S:'$L(S) TO="""" Q:TO=""""  I $E(S,6)[PT S:S3="""" S2=$O(^PK(S,S2)) S:$L(S2) S3=$O(^PK(S,S2,S3)) I $L(S3),$D(^PTG(S2,S3)) S TO=S_""|""_S2_""|""_S3 Q
 ;X ZAA02GS1 F jj=1:1 S:'$L(S3) S2=$O(^BK(PDOB,S2)) S:'$L(S2) TO="""" Q:TO=""""  S:$L(S2) S3=$O(^BK(PDOB,S2,S3)) I $L(S3),$S(S=0:1,$E($P($G(^GRG(S2)),"":"",7),1,$L(S))=S:1,1:0) S TO=S_""|""_S2_""|""_S3 Q
 ;
LOOKUPRF ;LOOKUP REFERRAL-CODE,ALPHA OR FREE TEXT - STORE FULL NAME
 I X["+" S X=$TR(X,"+") Q
 I 1 D:X[" " STRIP Q:X=""  I '$D(^RFG(X)),$E($O(^RFAH(X)),1,$L(X))=X K REFRESH D PRV2 D REFRESH K REFRESH
 S:X]"" X=$S($D(^RFG(X)):X_" "_$P(^RFG(X),":",2),1:X) I 1 Q
 Q
LOOKUPR ;LOOKUP REFERRAL BY NAME OR CODE - STORE CODE
 Q:X'?1.A.P  D:X[" " STRIP
 I $D(^RFG(X)),$P(^(X),":",25)'="Y" Q
 K REFRESH S X=$TR(X,LC_"?",UP) I $E($O(^RFAH(X)),1,$L(X))=X D PRV2 D REFRESH
 I 1 Q
PRV2 N:1 (X,ZAA02G,ZAA02GP,REFRESH) S REFRESH=1,Y="5,4\GRHLS\1\REFERRALS"
 S Y(0)="\EX\\$P(TO,""|"",2);4`$P(^RFG($P(TO,""|"",2)),"":"",2);25`$P(^RFG($P(TO,""|"",2)),"":"",4);20`$P(^RFG($P(TO,""|"",2)),"":"",6);10\"_X_"\\\"_X_"z" S ZAA02GPOPALT=$P($T(LOOKP),";",2,99)
 D ^ZAA02GPOP S:X["|" X=$P(X,"|",2) Q
 Q
LOOKP ;S S=$P(TO,""|""),S2=$P(TO,""|"",2) F jj=1:1 S:S2="""" S=$O(^RFAH(S)) S:S="""" TO="""" S:S]TEN TO=""""  Q:TO=""""  S:$L(S) S2=$O(^RFAH(S,S2),-1) I $L(S2),$D(^RFG(S2)),$P(^(S2),"":"",25)'=""Y"" S TO=S_""|""_S2 Q
REFRESH G AP0^ZAA02GFORM4
STRIP S %=$TR(X," ",""),%=$E(%,$L(%)),X=$E(X,1,$L($P(X,%,1,$L(X,%)-1)_%)) Q
 ;
 ;
T R "PAT-",X,! D LOOKUP Q
 Q
WP D ^ZAA02GWP G ^MNU
SCRIPT D ^ZAA02GSCRIPT G ^MNU
FAX D ^ZAA02GFAX G ^MNU
GETVAR ; LOAD INP ARRAY WITH DATA ACCORDING TO "VAR"
 D ^ZAA02GADS1
 Q
FINDSTY ; FIND STUDY(S) ON REPORT FOR SK
 K STUDY S A=.03,STUDY=0 F J=1:1 S A=$O(@ZAA02GWPD@(A)) Q:A=""  I $E($P(^(A),$C(1),4),1,5)=($C(27)_"[04m") S S=$P(^(A),$C(1),4) I S'["Conclusion"&(S'["CONCLUSION") D FINDS1
 Q
FINDS1 F J=1:1:$L(S,$C(27)) S S=$P(S,$C(27))_$E($P(S,$C(27),2,99),5,255)
 S STUDY=STUDY+1,STUDY(STUDY)=S Q
TS S ZAA02GWPD="^ZAA02GSCR(""TRANS"",DOC)" D FINDSTY W  Q
 ;
PAMI ; CHANGE HEADERS FOR PAPASTAVROS' ASSOCIATES
 ; to use - insert PAMI^ZAA02GSCRADS in the TRANSFER section of DISTRIB
 S ^ZAA02GWP(.9,DP,XDC,"XECUTE")="D PAMI2^ZAA02GSCRADS "_^ZAA02GWP(.9,DP,XDC,"XECUTE") Q
PAMI2 S $P(^ZAA02GWP(.9,DP,XDC,"DOC",.03),"\",13,14)=$TR($P(^ZAA02GWP(.9,DP,XDC,"DOC",.03),"\",13,14),1,2) Q
 ;
NOTES S INP("NOTES")=$P($G(^PTG(+$G(INP("MR")),1)),":",18) s opi="PDSP;NOTES;INP(""NOTES"")" X op Q
