ZAA02GSCML ;PG&A,ZAA02G-MTS,1.20,LETTER PROCESSING;30DEC94 4:14P;;;Wed, 05 DeC 2012  15:09
C ;Copyright (C) 1995, Patterson, Gray & Associates, Inc.
 ;
AVAIL ; determine available reports
 K D S D("EA")="",D("EB")=""
 K AV S A="" F J=1:1 S A=$O(@ZAA02GSCMD@(106,0,0,A)) Q:A=""  I $D(D(A)) S R="" F J=1:1 S R=$O(@ZAA02GSCMD@(106,0,0,A,R)) Q:R=""  S B=^(R) X B S:$T AV(R)=""
 S X="",Y=$O(AV("")) Q:Y=""  S Y=$O(AV(Y)) I Y="" S X=$O(AV("")) Q
 S Y="20,12\RLTHSO14U\1\Available Letters",Y(0)="\EX\AV\TO;8`$G(@ZAA02GSCMD@(106,TO));30"
 D ^ZAA02GPOP S X=$S(X[";EX":"",1:X) Q
 ;
 ;
T1 K AA S D=+$H D DATE^ZAA02GSCMR S DT=Y F J=1:1:19 S T="T"_J D COUNT I L'="" S AA(.1,J)=L
T2 S (J,Y,YY)="",A=1,B="Y" F  S J=$O(AA(.1,J)) Q:J=""  S $P(@B,"\",A)=$P($G(@ZAA02GSCM@("PARAM","LETTERS",J)),"\",6)_$S($G(AA(.1,J))>0:" ("_AA(.1,J)_")",1:"")_"\",AA(0,A)=J,A=A+1 S:$L(@B)>170 B="YY"
 S $P(Y,"\",A)="Quit\;",Y=Y_$E("ABCDEFGHIJKLMNOP1234567",1,A-1)_"Q;M A M M O G R A P H Y   L E T T E R S" K A
 S TC=25,TR=6,HP=2 D SEL^ZAA02GSCM I J'<NE K AA,DT Q
 D LETTER G T2
 ;
COUNT S L="" Q:'$D(@ZAA02GSCM@("LETTYP",T))  S L=0 Q:$O(^(T,""))>DT  S (A,B)="" F I=1:1 S A=$O(@ZAA02GSCM@("LETTYP",T,A)) Q:A=""  Q:A>DT  F I=1:1 S B=$O(@ZAA02GSCM@("LETTYP",T,A,B)) Q:B=""  S L=$S($D(SC("All")):1,1:$D(SC($P(^(B),",",3))))+L
 Q
 ;
FLUP S J=0,AA(0,J)=99,FLUP=1 D LETTER K AA,FLUP,DT Q
LETTER S ED=J,%R=1,%C=20,DOC=$P($G(@ZAA02GSCM@("PARAM","LETTERS",AA(0,ED))),"\",6)_" Letter" I AA(0,ED)=99 S DOC="FOLLOW-UP LIST"
 W @ZAA02GP,ZAA02G("HI"),$J("",42-$L(DOC)\2),DOC,$J("",44-$L(DOC)\2),!!,ZAA02G("CS")
ALT S TOP=3,SRC="@ZAA02GSCM@(""LETTYP"",""T"_AA(0,ED)_""",FP)",E="I 1",OF=-1,OF1=10000000,EP="9999999",FP="" D ^ZAA02GSCMTR Q
 ;
PRINT N (TSU,ZAA02G,TOP,ZAA02GP,DT,E,SDIR,SRC,ZAA02GSCM,ZAA02GSCMD,ZAA02GSCR,INX,IA,J,SC) S FP=$P(IA(J),",",3),MR=+IA(J),FPMR=$P(IA(J),",",2)
 S Y="20,7\HLD\1\\\Return without printing,*,Print only Selected Letter(s),Print ALL that are waiting,Fax/Print only Selected Letter(s),Fax/Print ALL that are waiting" S Y(0)="\EX" D POP Q:X[";EX"  Q:X=1  K IND
 G PRINTE
PRINTEVB S ZAA02GVB=1 G PRINTFX2
PRINTE ; PRINT ENTRY POINT
 S TYX=X G PRINTFX2:$G(ZAA02GVB),PRINTFX:$G(FAXPARAM)]"" S Y="33,10\HLDV\2\Select Printer\\" S X="" F J=1:1 S X=$O(^ZAA02GWP(96,X)) Q:X=""  S Y=Y_X_","
 S Y=$E(Y,1,$L(Y)-1),Y(0)="\EX" D POP Q:X[";EX"   S DV=X Q:DV=""
PRINTFX S %R=TOP+2,%C=1 W @ZAA02GP,ZAA02G("CS")
 S T=+$P(SRC,"""T",2),LTX=$P($G(@ZAA02GSCM@("PARAM","LETTERS",T)),"\",2),LTR="T"_T
 I LTX="" S %R=10,%C=15 W @ZAA02GP,*7,"No Letter Name is defined for this Letter",!!,?15,"FAX/PRINTING NOT STARTED - PRESS RETURN " R LTX#1 K LTX,LTR Q
 S %R=10,%C=25 W @ZAA02GP,"Letter(s) are Queued to ",$S(TYX>5:"Fax/Print ",1:"Printer "_DV) H 1
PRINTFX2 I '$D(ZAA02GSCR),$D(^ZAA02GSCR("ST",TSU,"PARAM","DATABASE")) S ZAA02GSCR=^("DATABASE")
 I '$D(ZAA02GSCRP) S $P(ZAA02GSCRP,";",3)=$G(@ZAA02GSCR@("PARAM","LOOKUP"))
 I $G(IND)=1 S FPDT=$G(@SRC@(FP,MR)) G QUEUE
 I TYX=3,'$D(INX) S FPDT="" D QUEUE
 I TYX=3!(TYX=5),$D(INX) S (MR,FP)="" F  S FP=$O(INX(FP)) Q:FP=""  F  S MR=$O(INX(FP,MR)) Q:MR=""  S:$E(INX(FP,MR))="T" LTR=INX(FP,MR) S FPDT=$G(@SRC@(MR)) I FPDT>0 D QUEUE
 I TYX'=3&(TYX'=5) D:LTR'[","  I LTR["," S SLTR=LTR F  S LTR=$P(SLTR,","),SLTR=$P(SLTR,",",2,999) Q:LTR=""  D
 . S FP="" F  S FP=$O(@SRC) Q:FP=""  Q:FP>DT  S MR="" F  S MR=$O(@SRC@(MR)) Q:MR=""  I $S($D(SC("All")):1,$P(^(MR),",",3)="":1,1:$D(SC($P(^(MR),",",3)))) S FPDT=^(MR) D QUEUE
 K TYX,A,B,Y Q
QUEUE S FPMR=+FPDT,DOC=+$G(@SDIR@(MR,FPMR,LTR,FP))
 S LTX=$P($G(@ZAA02GSCM@("PARAM","LETTERS",$TR(LTR,"T"))),"\",2)
 I DOC=0 D
 . I FPMR=0 S q=":" S:E["," q="," S FPMR=$P($G(E),q,2) Q:FPMR=0
 . S DOC=+$G(@ZAA02GSCM@("LETHIST",MR,FPMR,LTR,FP))
 Q:DOC=0
 I $P($G(@ZAA02GSCR@("TRANS",DOC,.011)),"`",9)'=MR D   Q
 . K @ZAA02GSCM@("LETTYP",LTR,FP,MR),@ZAA02GSCM@("LETMR",MR,FPMR,LTR,FP) K:$D(@ZAA02GSCM@("LETMR",MR,FPMR))<10 ^(FPMR)
 . S @ZAA02GSCM@("DELETED-EXAM",DOC)=$G(@ZAA02GSCM@("EXAM",DOC))
 I $TR($P($G(@ZAA02GSCR@("TRANS",DOC)),"`",13),"EH")'=$P($G(@ZAA02GSCR@("TRANS",DOC)),"`",13) Q
 K Y S Y("DIST")="LETTERS",Y=TSU I $P(FPDT,",",4)]"" S Y=$P(FPDT,",",4)
 S Y("EXAM")=$G(^ZAA02GSCMD("ST",Y,"EXAM",DOC))
 I TYX>4 S X=$P(Y("EXAM"),";",3),Y("FAX")=X  I $G(FAXPARAM)]"" S Y("FAX")=FAXPARAM,DV=$O(^ZAA02GWP(96,""))
 S Y("DOC")=DOC,Y("ZAA02GSCR")=$G(ZAA02GSCR),Y("TSU")=TSU,Y("ZAA02GSCM")=ZAA02GSCM,Y("ZAA02GSCMD")=ZAA02GSCMD,Y("ZAA02GSCRP")=ZAA02GSCRP,Y("FP")=FP,Y("FPMR")=FPMR,Y("MR")=MR,Y("LTX")=LTX,Y("SRC")=SRC,Y("LTR")=LTR,Y("IND")=$G(IND),Y("ZAA02GVB")=$G(ZAA02GVB)
 S DOC=$NA(@ZAA02GSCMD@(106,LTX))
 S CP=2,Y("XECUTE")="D PRINTX^ZAA02GSCML",Y("TYX")=TYX D QUEUE^ZAA02GSCRSP Q
 ;
PRINTX S CP=$P(^ZAA02GWP(.9,DP,XDC),"\",4) G:CP>1 PRNT ;skip around on copies 2+
 K INP S I="" F J=1:1 S I=$O(@VDOC@(I)) Q:I=""  S INP(I)=^(I)
 F I="LTX","ZAA02GSCM","ZAA02GSCMD","TSU","ZAA02GSCR","ZAA02GSCRP","FP","MR","DOC","FPMR","LTR","IND","EXAM","ZAA02GVB" S @I=INP(I)
 F I="PA1","PA2","PCSZ" K INP(I) ; FORCE NEW PAT ADDRESS LOOKUP
 I '$D(OPENDV),'$G(ZAA02GVB) D OPENDV^ZAA02GWPPC
 I $P($G(@ZAA02GSCM@("PARAM","LETTERS",$E(LTR,2,99))),"\",7)="L12" G L12^ZAA02GSCML1
 S C=0,ZAA02GWPD=$NA(^ZAA02GWP(.9,DP,XDC,"DOC")),DT=""
PRINTY D TMPL^ZAA02GSCRER,FETCH^ZAA02GSCRER S @ZAA02GWPD@(.011)=Y
 S DIR=106,REP=LTX,REPD=ZAA02GSCMD_"(106)" D:REP]"" CP K BT,REPD
 S SC=$P(EXAM,";",5)
 ; W ZAA02GSCM," ",MR," ",+FPMR," ",FP," ",LTR," ",REP," ",FP R CCC:300
 S C=","_(+$H)_$S($G(IND)=1:"I",1:"")_$S($D(@VDOC@("FAX")):"F",1:"")_":"
 S Y=TSU I $P($G(@ZAA02GSCM@("LETTYP",LTR,FP,MR)),",",4)]"" S Y=$P(^(MR),",",4)
 S ^(FP)=$S('$D(@ZAA02GSCMD@("ST",Y,"LETHIST",MR,FPMR,LTR,FP)):DOC,1:^(FP))_C
 ; I $G(IND)=1 G PRNT ; prevent PRINT from UTILITY from deleting queue
 I $D(@ZAA02GSCM@("LETMR",MR,FPMR,LTR,FP)) K @ZAA02GSCM@("LETTYP",LTR,FP,MR),@ZAA02GSCM@("LETMR",MR,FPMR,LTR,FP) I $D(@ZAA02GSCM@("LETMR",MR,FPMR))<10 K ^(FPMR)
PRNT Q:$G(ZAA02GVB)["Q"  D ^ZAA02GSCRMS1 S GET="C(I)=$P(^(I),XF,4)"
 Q
CP N ZAA02GSCR,B,LIST K INP("TEMPLATE1"),INP("TEMPLATE2"),INP("TEMPLATE3"),INP("TEMPLATE3")
 S INP("TEMPLATE")=REP,ZAA02GSCR=ZAA02GSCMD,HANDLE=$G(HANDLE,1) D COPY^ZAA02GSCRER1
 Q
 ;
CPOLD N B K VAR,D,MCE S (ALLVAR,B)="" F J=1:1:$L(TMPL,",") S B($P(TMPL,",",J))=""
 S UP="ABCDEFGHIJKLMNOPQRSTUVWXYZ",LC="abcdefghijklmnopqrstuvwxyz"
 I C=0 S B="",A=0 F J=1:1 S A=$O(@REPD@(REP,A)) Q:A=""  Q:A>.03  S D=$D(^(A)) S:D=1 @ZAA02GWPD@(A)=^(A) M:D>1 @ZAA02GWPD@(A)=@REPD@(REP,A)
 ; F J=1:1 S B=$O(@REPD@(REP,A,B)) Q:B=""  S @ZAA02GWPD@(A,B)=^(B)
 S PGMG=$G(^(.0113),$G(@ZAA02GWPD@(.03))) I $D(@ZAA02GWPD@(.0115,5))
 S (K,L)="",A=$O(@REPD@(REP,.03)) F J=1:1 S K=$O(@REPD@(REP,0,K)) Q:K=""  D:'$D(B(K)) CP1 F J=1:1 S L=$O(@REPD@(REP,0,K,L)) Q:L=""  S VAR(L)=$S($D(VAR(L)):VAR(L)_","_K,1:K)
 I $D(@REPD@(REP,.03)) S B=$TR($P(^(.03),"\",13,14)_","_$P(^(.03),"\",18),"\/",",,") F L=1:1:$L(B,",") S D=$P(B,",",L) I D'="",$O(@ZAA02GSCR@(110,D,0,""))'="" S K="" F J=1:1 S K=$O(^(K)) Q:K=""  D:'$D(B(K)) CP1
 I ALLVAR["RFA2"!(ALLVAR["RFCSZ") S ALLVAR=ALLVAR_"RFA2,RFCSZ"
 D:ALLVAR'="" ALLV
 F J=1:1 S A=$O(@REPD@(REP,A)) Q:A=""  S C=C+100,@ZAA02GWPD@(C)=C-100_$C(1,1,1)_$P(^(A),$C(1),4) I $D(VAR(A)) D CP2
 S @ZAA02GWPD@(C+100)=C_$C(1,1,1),^(C+200)=C+100_$C(1,1,1),C=C+200,J=$O(@ZAA02GWPD@(.03)) I J S $P(^(J),$C(1))=.03
 D:$D(MCE) CP^ZAA02GSCRCE K ALLVAR,VAR,D,B,BT Q
ALLV I $D(EDIT) S D=ALLVAR,ALLVAR="" F J=1:1:$L(D,",") S B=$P(D,",",J) I B]"" S INP(B)=B
 I ALLVAR]"" D ^ZAA02GSCRVB ; S B="" F J=1:1 S B=$O(D(B)) Q:B=""  I $G(INP(B))]"" S ^ZAA02GWP(.9,DP,XDC,B)=INP(B)
 K BT,ALLVAR Q
CP1 I $E(K)="$" Q
 I '$D(D(K)),'$D(INP(K)) S D(K)="",ALLVAR=ALLVAR_K_","
 Q
CP2 S L=$P(@ZAA02GWPD@(C),$C(1),4) F K=1:1:$L(VAR(A),",") S D=$P(VAR(A),",",K) I D'="" S T=$S($D(INP(D)):INP(D),1:"") D @($S($E(D)'="$":"F1",1:"F2")_"^ZAA02GSCRER1")
 I L=" " K @ZAA02GWPD@(C) S C=C-100 Q
 S $P(@ZAA02GWPD@(C),$C(1),4)=L Q
 ;
POP N TR D ^ZAA02GPOP Q
 ; CREATE MED RECORD SAMPLE FROM INPUT SCR
TEST S REP=$P($G(@ZAA02GSCM@("PARAM","INPUT")),"\",3+TYPS)  Q:REP=""
 S C=0,ZAA02GWPD="^ZAA02GTWP($J)",REPD=ZAA02GSCMD_"(106)" K @ZAA02GWPD D TMPL^ZAA02GSCRER D CP K BT,REPD
 S TL=4,MG=76,NM="",ZAA02GWPOPT="INQ" D ENTRY^ZAA02GWPV6 Q
 ;
TEXAM D EXAM("M",18993,"T9") Q
EXAM(TSU,DOC,LTR) ; PRINT FROM EXAM X AND FOR LETTER L
 N JOB S VDOC="^ZAA02GSCR(""TRANS"",DOC,.011)",ZAA02GSCM="^ZAA02GSCMD(""ST"",TSU)",ZAA02GSCMD="^ZAA02GSCMD",ZAA02GSCR="^ZAA02GSCR",ZAA02GSCRP=";;2",ZAA02GVB="1Q"
 S EXAM=$G(@ZAA02GSCM@("EXAM",DOC)),MR=$P(EXAM,";"),FPMR=$P(EXAM,";",2),FP="?"
 S LTX=$P($G(@ZAA02GSCM@("PARAM","LETTERS",$TR(LTR,"T"))),"\",2)
 K INP S I="" F J=1:1 S I=$O(@VDOC@(I)) Q:I=""  S INP(I)=^(I)
 F I="PA1","PA2","PCSZ" K INP(I) ; FORCE NEW PAT ADDRESS LOOKUP
 K ^ZAA02GTWP($J) S C=0,DT="",ZAA02GWPD="^ZAA02GTWP($J)",HANDLE=$G(HANDLE,1) D PRINTY
 S UP="ABCDEFGHIJKLMNOPQRSTUVWXYZ",LC="abcdefghijklmnopqrstuvwxyz"
 S VIEW=1 D ORTF^ZAA02GVBTER
 S ZAA02GFAXD(1)=B,ZAA02GFAXD="ZAA02GFAXD",JOB=-DOC_TSU_LTR D MEDPDF^ZAA02GVBTERP
 Q
