ZAA02GSCMIN2 ;ADS ; MAMMO UTILITIES;;;Fri, 23 May 2014  14:42
 ;
PENRAD ;
 S DD=$P($T(DATA),";",2,999)
 S ZAA02GSCR="^ZAA02GSCR",DIR="TRANS",NEWDIR="MAM" D INITLC^ZAA02GVBW
 S ZAA02GWPD="^ZAA02GSCR(DIR,DOC)",ZAA02GSCRP=";;3"
 S DOC=""
MORE F  S DOC=$O(^ZAA02GSCMD("ST","M","EXAM",DOC)) Q:DOC=""  S REC=^(DOC) D
 . Q:'$D(^ZAA02GSCR("TRANS",DOC))  K INP D FETCH^ZAA02GSCRER
 . S INP("TECH")=$P($P(REC,"OBT,",2),";")
 . S BB="",ALLVAR="" F Jj=1:1:$L(DD,",") S F=$P($P(DD,",",Jj),"-") I F]"",'$D(INP(F)) S ALLVAR=ALLVAR_F_","
 . D ^ZAA02GADS1
 . F Jj=1:1:$L(DD,",") S F=$P(DD,",",Jj) D
 .. I F="*" D  W ! Q
 ... W $E(BB,2,9999) I $P(BB,"|",2)'="EXAM" S BB="" Q
 ... S BB="" I $O(^ZAA02GSCR(DIR,DOC,.03))>0 S DIR2="TRANS"
 ... E  K Bc,Bcl D ZAA02GGETTX^ZAA02GVBTER1 S DIR2=NEWDIR
 ... S A=.03 F  S A=$O(^ZAA02GSCR(DIR2,DOC,A)) Q:A=""  S L=$P(^(A),$C(1),4) D
 .... I L'[$C(27) W L,"~" Q
 .... W $P(L,$C(27)) F JK=2:1:$L(L,$C(27)) W $E($P(L,$C(27),JK),5,999)
 .... W "~"
 .. I F["#" S BB=BB_"|"_$TR(F,"#") Q
 .. I F["-" S BB=BB_"|"_$$RE($P($G(INP($P(F,"-"))),",",+$P(F,"-",2))) Q
 .. S BB=BB_"|"_$S(F="":"",1:$G(INP(F)))
 . W $E(BB,2,99999),!! R CCC
 Q
RE(X) Q:$E(X)'=" " X Q $E(X,2,999)
DATA ;#EXAM,MR,STM,PLN,PFN,,,,BDT,SEX,,PA1,PA2,PCS-1,PCS-2,PZP,PTL,PWTL,SSN,,ACC,PROC1,PROC1T,DS,BIRAD,,,RF,PROVIDER,,,*,#REF,RF,RFL,RFF,,RFA1,RFA2,RFCS-1,RFCS-2,RFZP,RFTL,RFFAX,,*,#PLACE,SITENM,,,SITEC,*,#PROV,PV,,,,,PROVIDER,PNPI,,PVTEL,,,,*,#TECH,,,,,,TECH
