ZAA02GRPTFILES;;2018-03-08 17:31:39
 ; ADS Corp. Copyright
 q
 
MakeGroupsArr(outarr) //for dropdown
        n op n cnt
        s op="" s cnt=1
        s op=$O(^RPTSCH("GRP",op)) 
                while '(op="")
                {   
                        s cnt=cnt+1 
                        s outarr(cnt)=op_$C(9)_op
                        s op=$O(^RPTSCH("GRP",op))
                }
 q
 
GETCURRENT ; ZAA02Gweb writes out current configuration in tables
 N (%,RLC)
 n res,op,val,oth
 s res="", op="", val=""
        s op=$O(^RPTSCH("FOLDER","EXCEL",op)) 
                while '(op="")
                {   s val=^RPTSCH("FOLDER","EXCEL",op)
                        if $L(val) s val=$$TranslateToFullPath^ZAA02GUTILS2(val) s res=res_"<tr><td>"_op_"&nbsp </td><td> &nbsp "_val_"</td></tr>"
                        s op=$O(^RPTSCH("FOLDER","EXCEL",op))
                }
 if ($L(res)) s res="<table><tr><th>Scheduled Group</th><th> &nbsp Excel Folder</th></tr>"_res_"</table>"
                
 s oth=$G(^RPTSCH("FOLDER","EXCEL"))
 if $L(oth) s oth=$$TranslateToFullPath^ZAA02GUTILS2(oth) s res=res_"<br><table><tr><th>All other Scheduled Excel files</th></tr><tr><td>"_oth_"</td></table>"
.
 n fldr s fldr=$$GetReportsFolder^ZAA02GUTILS2()
 s res=res_"<br><table><tr><th>All other files generated by reports</th></tr><tr><td>"_fldr_"</td></table>"
 w res
 q
 
GETFOLDER ; ZAA02Gweb
 N (%,RLC)
 n oper, res
 s oper=$G(%("FORM","param1"))
 if (oper="") q
 if (oper="***ALL***") { 
                s res=$G(^RPTSCH("FOLDER","EXCEL")) 
        }
 else  { 
                s res=$G(^RPTSCH("FOLDER","EXCEL",oper))
        }
 w res
 q
.
SAVE ;ZAA02Gweb 
 N (%,RLC)
         n param1,param2, res s res=""
         s param1=$G(%("FORM","param1")) //folder name
         s param2=$G(%("FORM","param2")) //group name
         s param3=$G(%("FORM","param3")) //1 or 0 - all groups
         if ((param2="")&(param3="")) w "Parameters missing" Q //when called directly from URL
         
          if (($E(param1,2,2)=":") ! ($E(param1,1,2)="\\") ! ( param1[".." ) ) //assume it is already a full path if spFolder starts with \\ or *: 
                {   //*** DO NOT ALLOW LOCATIONS THAT ARE NOT UNDER THE NAMESPACE ***
                        s res = "<font color='red'> Not saved: location is invalid. </font>" ////spFolder  
                        w res
                        q
                }
        
         if (param3) { 
                s ^RPTSCH("FOLDER","EXCEL")=param1
                s res="Excel files folder : "_param1
         }
         else {
                if ($L(param2)) s ^RPTSCH("FOLDER","EXCEL",param2)=param1
                s res="Folder for group '"_param2_"': "_param1 
         }
         w res
 q
 
WriteOutNoPermission(usr,action)
  s action=$G(action) s usr=$G(usr)
  w "<font color='steelblue' face='verdana' title='"_usr _" - "_action_"'><br>Access denied. <br>Please verify your security settings.</font>"
  q
WriteOutInvalidHandle()
  w "<font color='steelblue' face='verdana'><br>Access denied. <br>Invalid handle, user is not logged in.</font>"
  q     
ST ;ZAA02Gweb
 N (%,RLC)
 s action="RPTFOLDERS"
 s lc="abcdefghijklmnopqrstuvwxyz",uc="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
 s usr  = $P($G(^ZAA02GVBUSER("WEB-LOGON",+$H,+$G(RLC)\1)),",",3)
.
 if $L(usr)=0 D WriteOutInvalidHandle Q
 if '$L(usr)||'($P($G(^OPG(usr,action)),":",1)) D WriteOutNoPermission(usr,action) Q
.
 s locOthers=$G(^RPTSCH("FOLDER","EXCEL")) 
 s currentConfig=""  
 W "<!DOCTYPE HTML>",!
 W "<html>",!
 W "<head>",!
.
        d WriteOutStyles
        d WriteOutScripts
.
 W "</head>"
.
 W "<body onload='showCurrentConfig()'>"
 W "<div hidden id='rlcBox'>"_RLC_"</div>" ,!
 
 W "<div><font face='verdana' size='2'>"_$ZDATETIME($H,5)_"</font></div>" ,!
 s PageTitle="Scheduled Reports Folders Setup"
 w "<div class='title1' title='Custom Folders'>"_PageTitle_"</div>",!
 w "<div class='hdr1'> &nbsp Set target location for <font color='green'>Excel</font> files produced by scheduled reports</div>",!
 w "<br>",!
 W " <div>  "  
 W " Common Excel files  folder "
 W "  <br><br> "
 W " &nbsp &nbsp &nbsp &nbsp  <input id='OthersFolder' type='textarea' value='"_locOthers_"' size=40/>  "
 W " &nbsp &nbsp <button class='btn' id='btnSave' "
       W "onclick=SaveFolder("
       W "document.getElementById('OthersFolder').value,'','1')"
       W "> &nbsp &nbsp Save  &nbsp &nbsp </button>"
 W " </div>  " 
.
 W "<br>  <div> "
 W "Set by group :<br><br>"
  W " &nbsp &nbsp  &nbsp for group &nbsp "
        n arrList
        D MakeGroupsArr(.arrList)
        W $$MakeDropdown^ZAA02GSETUTILS2("thisGroup",.arrList,"","'ShowAssigned()'",1) 
 W " <br><br>  &nbsp &nbsp  &nbsp use folder &nbsp <input id='thisFolder' type='textarea' value='' size=40/>  "
.
 W " &nbsp &nbsp <button disabled class='btn' id='btnSave1' "
       W "onclick=SaveFolder("
       W "document.getElementById('thisFolder').value,document.getElementById('thisGroup').value,'0')"
       W "> &nbsp  Save group  &nbsp </button>"
 W " </div>  "  
 W "<br>"
 w " <div class='msg1' id='statusMsg'></div>",!
 W " <div class='hdrNotes'>Notes:<br>1. 'Common Excel files folder' will be used for all groups that are not set up individually. "  
 W " <br>2. Clear the folder box to remove custom folder assignment."  
 W " <br>3. Requested folders will be created under the namespace folder ( "_$$GetNamespaceFolder^ZAA02GUTILS2()_" )"
 W " </div>",!
.
 W "<div class='msg2'>Current Configuration  &nbsp &nbsp <button class='refresh' onclick='showCurrentConfig()'>Refresh</button></div>"
 W "<div id='currDisp' class='msg3'>"
 W currentConfig_"</div>"
 W "</body>"
 
 W "</html>"
.
WriteOutScripts
 W "<script>",!
.
showRes 
  W "   function showRes(vals) { " 
  W "   document.getElementById('statusMsg').innerHTML=vals;  ", !
  W "   ; }  ", !
.
showCurrentConfig
 W " function showCurrentConfig() { "
 W " var res = callCache('GETCURRENT^ZAA02GRPTFILES','','','','','','',''); ", !
 W " document.getElementById('currDisp').innerHTML = res;   ",!
 W " } "
.
showAssigned
 W " function ShowAssigned() { "
 W " var oper = document.getElementById('thisGroup').value; ", !
 W " var res = callCache('GETFOLDER^ZAA02GRPTFILES',oper,'','','','','',''); ", !
 W " document.getElementById('thisFolder').value = res;   ",!
 W " document.getElementById('btnSave1').disabled=(oper==''); ",!
 W " showRes(''); } "
.
saveFolder
 W " function SaveFolder(folder,group,allgroups) { "
 W " var res = callCache('SAVE^ZAA02GRPTFILES',folder,group,allgroups,'','','',''); ", !
 W " showRes(res); showCurrentConfig()",! 
 W " } "
.
.
callCache               //call cache routine, routine name plus 7 params
 W "   function callCache(url,param1,param2,param3,param4,param5,param6,param7)",!
 W "   {var params = ""param1="" + param1 + ""&param2="" + param2 + ""&param3="" + param3 + ""&param4="" + param4 + ""&param5="" + param5 + ""&param6="" + param6 + ""&param7="" + param7;",!
 W "    var resp='';",!
 W "    resp = sendData(url, params);",!
 W "    return resp;" ,!
 W "   }",!
 
sendData
 W "   function sendData(href, args)",!
 W "   {"
 W "    var req = new XMLHttpRequest();",!
 W "    var response = '';",!
 W "    req.onreadystatechange = function()",!
 W "       {if (req.readyState == 4)",!
 W "           {response = req.responseText;",!
 W "           }",!
 W "       };",!
 W "    req.open(""POST"", href, false);",!
 W "    var ses=document.getElementById('rlcBox').innerHTML;  ", !
 W "    req.setRequestHeader('SES',ses) ; ", !
 W "    if (args)",!
 W "       {//req.setRequestHeader(""Content-Type"", ""application/x-www-form-urlencoded"");",!
 W "        //req.setRequestHeader(""Content-Length"", args.length);",!
 W "        req.send(args);",!
 W "       }",!
 W "    else req.send(null);",!
 W "    return response;",!
 W "   }",! 
.
 W "</script>",!
 Q
.
WriteOutStyles
 
 W "<style type='text/css'>"
 W "input{font-family:Verdana;}"
 //W "button.btn {height:25px; background-color:lightsteelblue; font-family:Verdana;} ",!
 W "textarea { margin: 0; width:75%; padding: 0; border-width: 1; }"
 W "div {font-family: Verdana;font-size:small; }",!
.
 W "div.title1 {font-family: Verdana;  text-align:center;line-height:40px;color:steelblue; font-size:medium;}",!
.
 W "div.hdr1 {font-family: Verdana; text-align:left; line-height:30px;color: white ; background-color:lightsteelblue; font-size:smallm;font-weight:bold;}",!
 W "div.hdr2 {font-family: Verdana; color:steelblue; font-size:small; font-weight:bold;}",!
.
 W "div.container {background-color:lightsteelblue;}",!
 W "div.hdrNotes {font-family: Verdana;  padding:20px; font-size:small;}",!
 W "div.msg1 {display:inline; color:gray; padding:20px; }",! 
 W "div.msg2 {font-weight: bold; font-family: Verdana; padding:4px; font-size:small;color:white;background-color:lightsteelblue;}",!
 W "div.msg3 {color:steelblue; width:75%;  margin-left:20px; padding:10px; }",! 
 W "th {text-align:left; }",! 
 W "table {border-spacing:5px;}",!
.
 W "</style>"
.
 Q
 
END //THE END 
  
  
.
