ZAA02GSCRINS ;PG&A,ZAA02G-SCRIPT,2.10,ZAA02GSCRIPT STATISTICS UPDATE;2OCT95 3:59P;;;29JAN2003  16:14
 ;
 Q
REBUILD ; REBUILD STATS FOR ALL - BACKGROUND - NO OUTPUT
 ; used when Transcription line counts where turned off and need to
 ; recompute
 S USER="XXX" D ^ZAA02GSCRPW R !!!,"Kill Current STATS? ",K I K="Y" K @ZAA02GSCR@("STATS") W " killed",!
 S A="" I K'="Y" R !,"Only documents without stats-",A,!!
 S ^ZAA02GSCR("STAT_REBUILD")=ZAA02GSCR_"`"_ZAA02GSCRP_"`"_A
 R "Direct or Background-",A,!!
 I A="B" J REB^ZAA02GSCRINS W "BACKGROUND JOB STARTED REBUILDING STATS" Q
 K  S DIRECT=1 D REB^ZAA02GSCRINS Q
 ;
REB S:1 $ZT="ERR^ZAA02GSCRINS" S ZAA02GSCRP=^ZAA02GSCR("STAT_REBUILD"),ZAA02GSCR=$P(ZAA02GSCRP,"`"),TYPR=$P(ZAA02GSCRP,"`",3),STARTDOC=$P(ZAA02GSCRP,"`",4),ZAA02GSCRP=$P(ZAA02GSCRP,"`",2)
 D SETUP^ZAA02GWP S XF=$C(1),TIME=0
 S ZAA02GSCRP=$TR(ZAA02GSCRP,"A"),LC="abcdefghijklmnopqrstuvwxyz",ZAA02GWPD=ZAA02GSCR_"(""TRANS"",DOC)"
 S:'$D(ZAA02GSCR) ZAA02GSCR="^ZAA02GSCR" S (ODT,DT)="",REBUILD=1 D TMPL^ZAA02GSCRER
 S DOC=$G(STARTDOC)
REBC F  S DOC=$O(@ZAA02GSCR@("TRANS",DOC),-1) Q:DOC=""  S B=$G(^(DOC)) D
 . I $G(DIRECT),DOC_" "["00 " W B,!
 . I +$G(^(DOC,.011,"STATS"))>0 S nocount=1 Q:TYPR="Y"
 . E  K nocount
 . D FETCH^ZAA02GSCRER
 . S DT=INP("DT"),YM=$P(DT,"/",3)+1900*100+DT S:YM<193000 YM=YM+10000 S DY=$P(DT,"/",2)
 . S A=INP("TR") I $D(@ZAA02GSCR@("PARAM","USER",A)),$P(^(A),"\",7)'="Y" Q
 . S TRTYPE="\Y",DCOUNT=OCOUNT D STATS^ZAA02GSCRER2
 Q
ERR S ^ZAA02GSCR("STAT_REBUILD","ERR",$G(DOC,"?"))=$ZE H 2 Q:$ZE["INRPT"  G REBC
 ;
A D ^ZAA02GSCRPW S ZAA02GSCRP=$TR(ZAA02GSCRP,"A"),LC="abcdefghijklmnopqrstuvwxyz",nocount=1 W ZAA02G("F") S ZAA02GWPD=ZAA02GSCR_"(""TRANS"",DOC)"
 R "ENTER BEGINNING DOC # - ",BDOC,! S:'$D(ZAA02GSCR) ZAA02GSCR="^ZAA02GSCR" K HIST
 S DOC=BDOC I $D(@ZAA02GSCR@("TRANS",DOC)) S DOC=DOC-1
 S ODT="" D TMPL^ZAA02GSCRER
B S DOC=$O(@ZAA02GSCR@("TRANS",DOC)) I DOC S B=$G(^(DOC)) I $D(^(DOC,.011,"STATS")) W:DOC#50=0 B,! D ST1 G B
 I DOC="" K nocount Q
 G B
ST1 D FETCH^ZAA02GSCRER
 I OCOUNT="" Q
 S DT=INP("DT"),YM=$P(DT,"/",3)+1900*100+DT S:YM<193000 YM=YM+10000,DY=$P(DT,"/",2)
 I ODT'=DT,'$D(HIST(DT)) S ODT=DT,HIST(DT)="" D CLEAR
 S A=INP("TR") I $D(@ZAA02GSCR@("PARAM","USER",A)),$P(^(A),"\",7)'="Y" Q
 S DCOUNT=OCOUNT D STATS^ZAA02GSCRER2
 Q
CLEAR W !,"DO YOU WANT TO CLEAR STATS FOR ",DT," ? " R A#1,! Q:A'="Y"
 S (A,B,C,D)=""
 F J=1:1 S A=$O(@ZAA02GSCR@("STATS",YM,A)) Q:A=""  W "." F J=1:1 S B=$O(@ZAA02GSCR@("STATS",YM,A,B)) Q:B=""  F J=1:1 S C=$O(@ZAA02GSCR@("STATS",YM,A,B,C)) Q:C=""  F J=1:1 S D=$O(@ZAA02GSCR@("STATS",YM,A,B,C,D)) Q:D=""  S E=$D(^(D,1)) F L=1:1:8 S $P(^(L),"+",DY)=0
 Q
 ;
SITE ; COMBINES TYPE STATS TO CREATE A SINGLE "NA" SITE LEVEL
 S (A,B,C,D)=""
 F J=1:1 S A=$O(@ZAA02GSCR@("STATS",A)) Q:A=""  F J=1:1 S B=$O(@ZAA02GSCR@("STATS",A,B)) Q:B=""  K ^(B,"SITEC")
 F J=1:1 S A=$O(@ZAA02GSCR@("STATS",A)) Q:A=""  F J=1:1 S B=$O(@ZAA02GSCR@("STATS",A,B)) Q:B=""  F J=1:1 S C=$O(@ZAA02GSCR@("STATS",A,B,"TYPE",C)) Q:C=""  S D=$O(^(C,C,1)) D SITE1
 Q
SITE1 F L=1:1:8 S E(L)=+$G(^(L))
 F L=1:1:8 S E=E(L),F=$G(@ZAA02GSCR@("STATS",A,"NA","SITEC",B,C,L)) F M=1:1:$L(E,"+") S:$P(E,"+",M)!(M=1) $P(^(L),"+",M)=$P(F,"+",M)+$P(E,"+",M)
 Q
 ;
TIMES ; CHECK FOR INCORRECT TIMES
 R "ENTER STARTING DOC # - ",DOC,! Q:DOC=""  S DOC=DOC-1
 F J=1:1 S DOC=$O(@ZAA02GSCR@("TRANS",DOC)) Q:DOC=""  I $D(^(DOC,.011,"STATS")) S B=^("STATS") I $P(B,",",7)>500!($P(B,",",7)<0) W DOC,?9,B,!
 Q
 ;
PROFILES R "ENTER STARTING DOC # - ",DOC,! Q:DOC=""  S A="" K T,^ZAA02GPROF
 S SP=$J("",80)
 F J=1:1 S A=$O(@ZAA02GSCR@("DIR",99,A)) Q:A=""  Q:^(A)<DOC  S D=$P(^(A),"`",8),T=+$P(^(A),"`",9)*3,D=$P(D,"/",3)*100+$P(D,"/")*100+$P(D,"/",2),^ZAA02GPROF(D)=$E($G(^ZAA02GPROF(D))_SP,1,T)_$J($TR($E($G(^(D)),T+1,T+3)," ")+1,3)_$E($G(^(D))_SP,T+4,72)
PP S B=0,A="" F  S A=$O(^ZAA02GPROF(A)) Q:A=""  S C=$E(A,3,4) X:B'=C "S B=C W !?7 F J=0:1:23 W $J(J,3) W:J=23 !!" W A," ",^(A),!
 Q
 ;
COPY W !,"COPY TO WHAT NEW STAT HEADING " R HD Q:HD=""
 S (A,B,C,D)=""
 F J=1:1 S A=$O(@ZAA02GSCR@("STATS",A)) Q:A=""  W "." F J=1:1 S B=$O(@ZAA02GSCR@("STATS",A,"NA",B)) Q:B=""  I B'="SITEC" F J=1:1 S C=$O(@ZAA02GSCR@("STATS",A,"NA",B,C)) Q:C=""  F J=1:1 S D=$O(@ZAA02GSCR@("STATS",A,"NA",B,C,D)) Q:D=""  D COPY99
 Q
COPY99 S E=^(D,1) F L=1:1:7 S E(L)=^(L)
 S @ZAA02GSCR@("STATS",A,HD,B,C,D,1)=E(1) F L=2:1:7 S ^(L)=E(L)
 Q
 ;
COPYTR ; COPY ENTIRE DATABASE
 S (A,B,C,D)=""
 S UP="ABCDEFGHIJKLMNOPQRSTUVWXYZ",LC="abcdefghijklmnopqrstuvwxyz"
 F  S A=$O(^ZAA02GSCR("PROV",A)) Q:A=""  S PROV(+A)=$TR($P(^(A),"\"),LC,UP)
 S A=200000,L=$O(^ZAA02GSCR("TRANS",A),-1)+100
 W "Searching TRANS starting at ",A," - Will renumber starting with ",L,!,"Press RETURN to begin " R CC
 F L=L:1 S A=$O(^ZAA02GSCR("TRANS",A)) Q:A=""  W "." S:$D(^(A))#2 ^NZAA02GSCR("TRANS",L)=^(A) D COPYTRX
 W !,"Finished copying into ^NZAA02GSCR - kill off old reports, copy NZAA02GSCR and then",!,"run DIR to rebuild directory items." Q
COPYTRX F  S B=$O(^ZAA02GSCR("TRANS",A,B)) Q:B=""  S:$D(^(B))#2 ^NZAA02GSCR("TRANS",L,B)=^(B) F  S C=$O(^ZAA02GSCR("TRANS",A,B,C)) Q:C=""  S:$D(^(C))#2 ^NZAA02GSCR("TRANS",L,B,C)=^(C)
 Q
 S E=^NZAA02GSCR("TRANS",L,.011) Q:E=""  S F=$P(E,"`",6),$P(E,"`",20)=F,$P(E,"`",6)=$S(F?1.A:"RA",1:"MR"),F=+$P(E,"`",7),$P(E,"`",7)=F_" "_$G(PROV(F)),^(.011)=E Q
 Q
 ;
Y2K ; UPGRADE STATS TO INCLUDE CENTURY
 S A="" S:$D(ZAA02GSCR)=0 ZAA02GSCR="^ZAA02GSCR" F  S A=$O(@ZAA02GSCR@("STATS",A)) Q:A=""  I A<190000 S B=$S(A>3000:190000+A,1:200000+A) M @ZAA02GSCR@("STATS",B)=@ZAA02GSCR@("STATS",A) K @ZAA02GSCR@("STATS",A)
