ZAA02GSCRCHM ;PG&A,ZAA02G-SCRIPT,2.10,INTERFACE ROUTINE FOR COLUMBIA MED PLAN;09FEB94  14:26;12DEC94 10:03A;;31AUG99  15:25
 ;
LOAD ;LOADS INP ARRAY FOR ID WITH PATIENT INFO. GIVEN INTERNAL #
 D LOADX I X S K=$P($G(^[DBASE]MB8(X,"M"," "_INP("MR"),11)),"|",3) I K]"" S K=$P($G(^[DBASE]DI1T(K,1)),"|",6) S INP("LOC")="-"_K
 S K=0 F J=1:1 S A=$P("MR,PATIENT,DOB,REV,LOC,AGE",",",J) Q:A=""  I $D(INP(A)) S K=K+1,opi(K)="PDSP;"_$P("MR,PATIENT,DOB,CONSULT2,LOC,AGE",",",J)_";INP("""_A_""")"
 S opi=K,SRF=rf,rf=ZAA02G("HI") x:K op S rf=SRF K SRF,A
 I 1 S RX=4 Q
 Q
LOADX N (ZAA02G,X,INP,DBASE) S A=$G(^[DBASE]MB0(X,2)),INP("PATIENT")=$P(A,"|"),INP("MR")=$TR($P(A,"|",5)," ",""),D=$P(A,"|",3),DT="" D:D]"" DATE S INP("DOB")=DT,INP("REV")=$P(A,"|",2),INP("PIN")=X D AGE S INP("AGE")=T
 Q
 ;
LOOKUPN ; LOOKUP BY EITHER CHART # OR SSAN
 I X=0 S INCOMP=0,RX=1 Q
 I X="00" S RX=1 Q
 I X?1"M"1.N S X=$E(X,2,7) Q
 I X["+" G LOOKUPN^ZAA02GSCRCH2
 S X=$TR(X,"@+") I X?1.AP D LOOKUP Q:X=""  S X=$G(INP("MR")),RX=4 Q
 N FILE S FILE="^[DBASE]"_$S(X?9N:"MB3",1:"MB02")
 S PAT=$S(X?9N:X,1:" "_($E(X,1,6)))
 I $D(@FILE@(PAT)) S X=$O(@FILE@(PAT,"")) G LKN1:$O(^(X)),LKN2
 I $E($O(@FILE@(PAT)),1,$L(PAT))'=PAT X "I 0" G LOOKE
LKN1 S ZAA02GPOPALT=$P($T(LOOKTN),";",2,99),REFRESH=1
 D LOOK1 S tt=+REFRESH,td=$P(REFRESH,":",2) D AP0^ZAA02GFORM4
 I PAT[";EX" S X="" Q
 S X=$P(PAT,"|",2)
LKN2 D LOAD S X=INP("MR") K i,jj,PAT Q
 ;
LOOKUP ; LOOKUP IN THE HSI PATIENT FILE BY NAME
 I X="" W "Enter starting letters" H 2 G LOOKE
 S X=$TR(X,LC_"?",UP),PT=$P(X,",",2),PAT=$P(X,","),REFRESH=1 G:PAT="" LOOKE
 I $E($O(^[DBASE]MB1(PAT)),1,$L(PAT))'=PAT G LOOKE
 I PT'="" S i=PAT F jj=1:1 S i=$O(^[DBASE]MB1(i)) Q:i=""   Q:$E($O(^[DBASE]MB1(i)),1,$L(PAT))=PAT&($E($P(i,",",2),1,$L(PT))=PT)  I $E($O(^[DBASE]MB1(i)),1,$L(PAT))'=PAT G LOOKE
 S ZAA02GPOPALT=$P($T(LOOKT),";",2,99)
 D LOOK1 S tt=+REFRESH,td=$P(REFRESH,":",2) D AP0^ZAA02GFORM4
 I PAT[";EX" S X="" Q
 S X=$P(PAT,"|",2) D LOAD S X=INP("PATIENT")
LOOKE K i,jj,PAT Q
 ;
LOOK1 N:1 (FILE,ZAA02GPOPALT,DBASE,ZAA02G,ZAA02GP,PAT,PT,REFRESH) S Y="15,3\RLHS\1\PATIENT LOOKUP\   NAME                   CHART#     DOB       SSAN  "
 S Y(0)="\EX\\$P(^[DBASE]MB0($P(TO,""|"",2),2),""|"");23`$P(^(2),""|"",5);8R`$$DOB^ZAA02GSCRCHM($P(^(2),""|"",3));10R`$P(^(2),""|"",4);9\"_PAT_"\\\"_PAT_"z"
 S ZAA02GS1="S S=$P(TO,""|""),S2=$P(TO,""|"",2)"
 D ^ZAA02GPOP S PAT=X Q
 ;
LOOKT ;X ZAA02GS1 F jj=1:1 S:S2="""" S=$O(^[DBASE]MB1(S)) S:jj=999 TO="""" S:S]TEN TO=""""  Q:TO=""""  I $E($P(S,"","",2),1,$L(PT))=PT S S2=$O(^[DBASE]MB1(S,S2)) I $L(S2),$D(^[DBASE]MB0(S2,2)) S TO=S_""|""_S2 Q
 ;         
LOOKTN ;X ZAA02GS1 F jj=1:1 S:S2="""" S=$O(@FILE@(S)) S:jj=999 TO="""" S:S]TEN TO=""""  Q:TO=""""  S S2=$O(@FILE@(S,S2)) I $L(S2),$D(^[DBASE]MB0(S2,2)) S TO=S_""|""_S2 Q
 ;
LOOKUPR ; LOOKUP REFERRAL BY NAME/NUMBER - ALLOW FREE TEXT
 I X]"",$D(@ZAA02GSCR@("PARAM","REF",X)) S X=$P(^(X),"\",3) Q
 I X'?1.N Q
 Q
 ;
LOOKUPRH S x0=X D PRV3 D:$D(REFRESH) REFRESH S:X[";EX" X="" S:X="" X=x0 I X]"",$D(@ZAA02GSCR@("PARAM","REFA",X)) S X=$P($G(@ZAA02GSCR@("PARAM","REF",^(X))),"\",3)
 I 1 Q
PRV3 N:1 (X,ZAA02G,ZAA02GP,REFRESH,ZAA02GSCR) S REFRESH=1,Y="10,4\GRHLS\1",Y(0)="\EX\@ZAA02GSCR@(""PARAM"",""REFA"")\TO;25`@ZAA02GSCR@(""PARAM"",""REFA"",TO);5\"_X_"\\\"_X_"z" D ^ZAA02GPOP Q
 ;
REFRESH G AP0^ZAA02GFORM4
 ;
VAR ; LOAD INP ARRAY WITH DATA ACCORDING TO "VAR"
 F I=1:1 S VAR=$P(ALLVAR,",",I) Q:VAR=""  D VAR1
 Q
VAR1 Q:VAR=""  Q:$T(@VAR)=""  D @VAR S INP(VAR)=T Q
NOTES S T="NOTES FROM ZAA02GSCRMID" Q
DR S T=$P($G(INP("PROVIDER"))," ") Q:T=""  S T=$P($G(@ZAA02GSCR@("PROV",T)),"\",3) Q
DRI D DR Q:T=""  S T=$P(T,","),T=$E(T)_$E($P(T," ",2))_$E($P(T," ",3)) Q
AGE S T=$G(INP("DOB")) Q:T=""  D JULIAN Q:T=""  S tt=T,T=$S($D(INP("DT")):INP("DT"),1:$H) D:T["/" JULIAN S T=T-tt\365.25 K tt
 Q
CCX1 S T="" S:$G(INP("CC1"))]"" T="CC: "_INP("CC1") Q
CCX2 S T="" S:$G(INP("CC2"))]"" T="CC: "_INP("CC2") Q
SEX S T="" S:$G(INP("REV"))]"" T=INP("REV") Q
SITE S T="" I $G(INP("SITEC"))]"" S T=$G(@ZAA02GSCR@("PARAM","SITE",INP("SITEC"))) Q
AUTH S T="A: " S:$D(DOC) T=T_" "_DOC Q
 F J=.0172:.0001 Q:'$D(@ZAA02GSCR@("TRANS",DOC,J,.0189))  S Y=Y_"   "_$S(J=.0172:"Original Document",1:"Amended Document ")_"    amended on "_$$DT(^(.0189))_",",B(B)=J,B=B+1
 ;
 ;
 ; USED BY AGE CALCULATION
JULIAN S m=+T-3,d=$P(T,"/",2),y=$P(T,"/",3) I (m+d+y)<-2 S T="" Q
 S:y<100 y=y+1900 S o=$S(y<1900:-14917,1:21608),y=y>1999*100+$E(y,3,4) S:m<0 m=m+12,y=y-1 S T=1461*y\4,T=153*m+2\5+T+d+o K m,y,o,d Q
 Q
DOB(D) N (D,ZAA02G) D DATE Q DT
DATE S K=D>21608+305+D,Y=4*K+3\1461,D=K*4+3-(1461*Y)+4\4,M=5*D-3\153,D=5*D-3-(153*M)+5\5,M=M+2,Y=M\12+Y+1840,M=M#12+1,K="/",Y=Y*100+M*100+D,DT=$E(Y,5,6)_K_$E(Y,7,8)_K_$E(Y,1,4) Q
 ;
DTTMX N (DTTM) S D=$H D DATE
 S TM=$P($H,",",2)\60,DTTM=DT_"  "_$E(TM\60+100,2,3)_":"_$E(TM#60+100,2,3) Q
 ;
BOLD ; BOLDING LOGIC FOR CHP REPORTS
 ; SCAN REPORT & BOLD PATIENT INFO & IMPRESSION
 ;     FORMAT ASSUMED: (only looks for Capitalized lines)
 ;        XXXXX:  xxxxx          bolded ONE LINE
 ;        IMPRESSION:  xxxx      Bold until next XXXX:
 ;
 D DTTMX S @VDOC@("DTTM")=DTTM Q:$G(@VDOC@("PROC2"))="LTR"
 D REVERS^ZAA02GWPPC1 Q:'$D(ZAA02G("ron"))  S K=.03,K1=ZAA02G("ron"),K2=ZAA02G("rof")
BOLD0 F J=1:1 S K=$O(@ZAA02GWPD@(K)) Q:K=""  D
 . I $P(^(K),$C(1),4)?1.UP1":".E S $P(^(K),$C(1),4)=K1_$S($P(^(K),$C(1),4)'?1.UNP:$P($P(^(K),$C(1),4),":")_":"_K2_$P(^(K),":",2,99),1:$P(^(K),$C(1),4)_K2)
 . I $P(^(K),$C(1),4)["   ADDENDUM REPORT" S $P(^(K),$C(1),4)=K1_$P(^(K),$C(1),4)_K2
 K K1,K2,K3 Q
 ;
PREEDIT ; INITIALIZATION FROM ID BLOCK FOR PATHOLOGY
 S:'$D(INP("CONSULT")) INP("CONSULT")="" S INP("DIST")=1,OLDAC=$G(INP("TEMPLATE2")),OLDDS=$G(INP("DS")),OLDDRT=$G(INP("DRT"))
 Q
 ;
CHKFILE ; CHECK FOR UNIQUE ACCESSION # FOR PATHOLOGY
 I $D(^KPATH("AC",X)),$P(^(X),"|",3)'=$G(DOC) X "I 0" S A="DUPLICATE ACCESSION # IN REPORT # "_$P(^(X),"|",3) Q
 I 1 S INP("TEMPLATE")=$E(" ncs",$F("NCS",$E(X))) Q
 ;
UPDTFILE ; UPDATE CARD FILE INFORMATION AT END OF ID BLOCK (RSL CODE)
 S X=INP("TEMPLATE2") I $G(OLDAC)]"",X'=OLDAC K ^KPATH("AC",OLDAC)
 S ^KPATH("AC",X)=INP("MR")_"|"_INP("PATIENT")_"|"_DOC
 S X=INP("DS") I $G(OLDDS)]"",X'=OLDDS K ^KPATH("DR",OLDDS,DOC)
 S:X]"" ^KPATH("DR",X,DOC)=INP("MR")_"|"_INP("PATIENT")_"|"_INP("TEMPLATE2")
 S X=$G(INP("DD")) I $G(OLDDRT)]"",X'=OLDDRT K ^KPATH("DRT",OLDDRT,DOC)
 S:X]"" ^KPATH("DRT",X,DOC)=""
 Q
BUILD S A="" F  S A=$O(^ZAA02GSCR("TRANS",A)) Q:A=""  S B=$P($G(^(A,.011)),"`",11) I B]"" S ^KPATH("DRT",B,A)=""
 Q
 ;
 ; SHOW SPECIMEM SOURCE WITH SELECT KEY
AW S F=OF*IA(J)+OF1,D=^(OJ) W @ZAA02GP,ZAA02G("RON"),$TR($P(D,"`",1,3),"`~","  "),ZAA02G("ROF")," ",ZAA02G("CL"),ZAA02G("RON"),"SP SRC: "
 W $E($P($G(@ZAA02GSCR@("TRANS",F,.011)),"`",2),1,40) W ZAA02G("ROF") K D I $D(@SDIR@(0))'=3 Q
