%ZAA02GEDU0 ;;%AA UTILS;1.24;UTIL: UTILITIES MENU;30MAY91  14:36
        ;;Copyright (C) 1990,91 Patterson, Gray & Associates, Inc. ;
        ;;All rights reserved. ;
        S UTL=1
UTIL S %R=bl+2,%C=lm-1,Y=%C_","_%R_"\H\HL,EX\Utilities: \\QUIT,ROUTINE,GLOBAL,EXPORT,IMPORT" W @ZAA02GP,tCL_tLO D ^ZAA02GEDPL I ZAA02GF="HL" S HN=2000 D HELP G UTIL
        I X=1!(ZAA02GF="EX") K X,Y,PR,SF Q
        S PR=$P("/ROUT/GLOB/EXP/IMP","/",X),SF=0 D @PR I $D(UTL),$D(SF),SF D SETUP^ZAA02GED,NP^ZAA02GED00
        G UTIL
PAIN S SF=1 X:rm>79 ZAA02G(80) D ZAA02GPAINT X:rm>79 ZAA02G(132) Q
FORM S SF=1 X:rm>79 ZAA02G(80) D ZAA02GFORM X:rm>79 ZAA02G(132) Q
IMP D ^ZAA02GEDUI0 Q
EXP D ^ZAA02GEDUE0 Q
ZAA02GPAINT ;N (ZAA02G,ZAA02GP) D ^ZAA02GPAINT Q
ZAA02GFORM ;N (ZAA02G,ZAA02GP) D ^ZAA02GFORME Q
ROUT S %R=bl+2,%C=lm-1,Y=%C_","_%R_"\H\HL,EX\Routines: \\QUIT,LIST,SRCH,REPL,DIR,COMP,ARCH,PURG,RELEASE" W @ZAA02GP,tCL_tLO D ^ZAA02GEDPL I ZAA02GF="HL" S HN=2100 D HELP G ROUT
        I X=1!(ZAA02GF="EX") K X,Y,PR,SF Q
        S PR=$P("/RLIST/SRCH/REPL/DIR/COMP/ARCH/PURG/VERS","/",X),SF=0 D @PR I $D(UTL),$D(SF),SF D SETUP^ZAA02GED,NP^ZAA02GED00
        G ROUT
SRCH D ^ZAA02GEDUS0 Q
REPL D ^ZAA02GEDUS1 Q
RLIST D ^ZAA02GEDP0 Q
DIR D ^ZAA02GEDP1 Q
COMP D MULT^ZAA02GEDR0 Q
ARCH D MULT^ZAA02GEDA0 Q
PURG D ^ZAA02GEDD0 Q
VERS D ^ZAA02GEDUR Q
GLOB S %R=bl+2,%C=lm-1,Y=%C_","_%R_"\H\HL,EX\Globals: \\QUIT,EDIT,LIST,COPY" W @ZAA02GP,tCL_tLO D ^ZAA02GEDPL I ZAA02GF="HL" S HN=2300 D HELP G GLOB
        I X=1!(ZAA02GF="EX") K X,Y,PR,SF Q
        S PR=$P("/GEDIT/GLIST/GCOPY","/",X),SF=0 D @PR I $D(UTL),$D(SF),SF D SETUP^ZAA02GED,NP^ZAA02GED00 K SF
        G GLOB
GEDIT D EDIT^ZAA02GEDGE Q
GLIST D ^ZAA02GEDG0 Q
GCOPY D ^ZAA02GEDGC Q
XREF S %R=bl+2,%C=lm-1,Y=%C_","_%R_"\H\EX\Cross Reference: \\QUIT,ANALYZE,PRINT" W @ZAA02GP,tCL_tLO D ^ZAA02GEDPL I X=1!(ZAA02GF="EX") K X,Y,PR Q
        S PR=$P("/XANAL/XPRNT","/",X) D @PR G XREF
XANAL D ^ZAA02GEDXR Q
XPRNT D ^ZAA02GEDXR1 Q
HELP D ^ZAA02GEDH,RESTORE^ZAA02GED08(+REFRESH,$P(REFRESH,":",2)) K REFRESH Q
NA W pBL_tLO_"Not Available"_$J("...press any key",rm-lm-11) R *X Q
        ;
